language: python
cache: pip
dist: xenial
python:
    - '2.7'
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    - pypy
    - pypy3
env:
    - TOXENV=py-toml
    - TOXENV=py-notoml
install:
    - pip install codecov tox
script:
    - tox
after_success:
    - codecov
